version: '3.1'

services:
  # БД для сервиса управления заметками
  db_notes:
    # Название контейнера
    container_name: db_notes
    # Значения переменных окружения
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    # Образ для контейнера который будет скачан из DockerHub
    image: mongo:5.0.25
    # Меняем порт MongoDB в контейнере
    command: mongod --port ${MONGO_INITDB_PORT}
    # Порты, которые будут использоваться в контейнере
    ports:
      - ${MONGO_INITDB_PORT}:${MONGO_INITDB_PORT}
    # Настройки хранилища данных, необходим для сохранения
    # данных в базе данных при остановке контейнера
    volumes:
      - db_notes_vol:/var/data/db/data/configdb
    # Объявляем внутренную сеть докера, для 
    # передачи данных между контейнерами
    networks:
      - server_net

  redis_notes:
    # Название контейнера
    container_name: redis_notes
     # Образ для контейнера который будет скачан из DockerHub
    image: redis:7.2.4
    # Меняем порт Redis в контейнере
    command: --port ${REDIS_PORT}
    # Порты, которые будут использоваться в контейнере
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    # Настройки хранилища данных, необходим для сохранения
    # данных в базе данных при остановке контейнера
    volumes:
      - redis-data:/data
    # Объявляем внутренную сеть докера, для 
    # передачи данных между контейнерами
    networks:
      - server_net
  # Сервис для управлением заметками 
  notes:
    # Название контейнера
    container_name: notes 
    # Папка контейнера для сборки
    build: ./notes
    # Указывает, что контейнер должен ждать запуск контейнеров
    # Так как необходимо, чтобы MongoDB и Redis были запущены 
    depends_on:
      - db_notes 
      - redis_notes
    # Объявляем внутреннюю сеть докера, для 
    # передачи данных между контейнерами
    networks:
      - server_net
    # Порты которые будут использоваться в контейнере
    ports:
      - ${NOTES_PORT}:${NOTES_PORT}
    # Внешние переменные окружения
    environment:
      # Порт который будет использоваться в контейнере
      NOTES_PORT: ${NOTES_PORT}
      # Секретный ключ для аутентификации
      JWT_SECRET: ${JWT_SECRET}
      # Настройки MongoDB, указываем в контейнере 
      MONGO_INITDB_HOST: ${MONGO_INITDB_HOST}
      MONGO_INITDB_PORT: ${MONGO_INITDB_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      # Настройки Redis, указываем в контейнере
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
# Конфигурация для хранилища данных
volumes:
  db_notes_vol: {}
  redis-data: {}

# Настройки сетей
networks:
  server_net:
    driver: bridge
